DROP TABLE IF EXISTS Evaluation;
DROP TABLE IF EXISTS Itineraire;
DROP TABLE IF EXISTS Inscription;
DROP TABLE IF EXISTS Arret;
DROP TABLE IF EXISTS Voyage;
DROP TABLE IF EXISTS Voiture;
DROP TABLE IF EXISTS Etudiant;;